### ISSUE TITLE
Method AuthMigrator.getInstance().migrate() is unresolvable, provided fix causes crashes and slow start

### ISSUE THREAD

**Issue by HarisSistek** [firebase/digits-migration-helper-android#3] opened 2017-09-21 07:24 UTC
## Preface

Have had a bit back-and-forth communication with the support team at fabric about this migration. They suggested I create and issue and document what I'm seeing here.

### Project Gradle dependencies:
```
 dependencies {

    classpath 'com.android.tools.build:gradle:2.3.3'
    classpath 'com.google.gms:google-services:3.1.0' // google-services plugin

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```
### App Gradle dependecies

```
compileSdkVersion 26
buildToolsVersion '26.0.1'
minSdkVersion 19
targetSdkVersion 26

    // digits migration helper
    compile 'com.google.firebase:firebase-core:11.2.2'
    compile 'com.google.firebase:firebase-auth:11.2.2'
    compile 'com.firebase:digitsmigrationhelpers:0.1.1'
```

## Main Issue:

When trying to follow the guide at: https://firebase.google.com/support/guides/digits-android

My .migrate() method comes up as unresolvable, since the only two migrate methods present are:
1. one with a needed boolean param
2. RedeemableDigitsSessionBuilder param.

![image](https://user-images.githubusercontent.com/2276291/30683103-5736db8a-9eac-11e7-80e3-542ed8b56135.png)

The support staff suggested using this instead:

```java
        AuthMigrator.getInstance().migrate(!BuildConfig.DEBUG).addOnCompleteListener(
                new OnCompleteListener<Void>() {

                    @Override
                    public void onComplete(@NonNull Task<Void> task) {
                        FirebaseUser u = FirebaseAuth.getInstance().getCurrentUser();
                        if (u != null) {
                            // Either a user was already logged in or token exchange succeeded
                            Log.d("MyApp", "Digits id preserved:" + u.getUid());
                            Log.d("MyApp", "Digits phone number preserved: " + u.getPhoneNumber());
                        } else {
                            // No tokens were found to exchange and no Firebase user logged in.
                        }
                    }
                });
```

Which solved the unresolvable error, but caused **slow load times (15-30 seconds)** on newer devices such Samsung Galaxy s6 (SM-G920F, android version: 7.0 )and Sony Xperia XZS (G8231, android version 7.1.1) , but on older devices like Samsung Galaxy S4 (GT-I9505, android version: 5.0.1) the device `just crashes after showing a white screen in about 10 seconds and the app wont start. 

The **testers/users can solve the issue by clearing both app and buffer data**, and just perform a phone number authentication as normal. After that the load times are back to normal and app start right away.

**Comment by ashwinraghav** [comment] 2017-09-22 02:37
@HarisSistek : Thanks for reaching out. The .migrate(!BuildConfig.DEBUG) is the recommended implementation. Some questions to help us understand the issue better:
1. Are you calling the migrate method in your Application class or Activity ?
2. Can you show us the implementation of your onCompleteListener ? The one you have pasted above serves as an example showing how token exchange cases can be handled. Apps are expected to use it only as reference. A complete example on a listener can be found [here](https://github.com/firebase/digits-migration-helper-android/blob/master/app/src/main/java/com/migrantdigitsapplication/digits/MainActivity.java#L62)
3. Can you give us a stacktrace for the crash report?

As for load times, if your application waits for the migrate methods's `onComplete()` callback before starting, that might marginally increase load times. Note that the migrate method is a no-op once tokens are exchanged and deleted. So this would (marginally) slow down app load time only the first time after they receive your new update. But the expected delay is just a second or so. 15 seconds seems unlikely.

**Other minor suggestions:**
_Change google services plugin version_:
```groovy
classpath 'com.google.gms:google-services:3.0.0'
```

_Change firebase versions_:
```groovy
compile 'com.google.firebase:firebase-core:11.0.0'
compile 'com.google.firebase:firebase-auth:11.0.0'
```

**Comment by HarisSistek** [comment] 2017-09-22 06:17
@ashwinraghav Thank for the reply.

After you showed us the example [here](https://github.com/firebase/digits-migration-helper-android/blob/master/app/src/main/java/com/migrantdigitsapplication/digits/MainActivity.java#L62) I think we have implemented our migration wrongly.

Answers to questions:
1. Calling the migrate method in Application class, with the code snippet above.
2.  We were using the code snippet suggested by the guide/staff above that I already provided, and I see now with the  example code you provided that is probably whats causing our issue, since we aren't waiting on the migration to complete as you are in the example.
3. Never were any stack traces (should not used the word crashed here), test users just reported a white screen, and than some time out popup. I'l try to translate it from Norwegian to English it would sound something like. "App has timed out/waiting to long" with an "exit" and "wait" buttons. We assume it was a crash, I see now that our app probably just was stuck.

We will try to implement as shown in you example, and get back to you.

**Comment by HarisSistek** [comment] 2017-09-22 13:21
@ashwinraghav Here is an update.

Tried both implementations now and still the same issue. After further searching and debugging the logs we have pinpointed the moments the delay occurs. The strange thing is that it occurs after the migration happens, and now I'm unsure if the migration is the main cause even though its the only new element in the code.

Here is sequence of logs that usually would have taken some milliseconds (AsyncTask that does API call to our backend). Normally I would see no more than 100-300 ms between the these two lines and the app would continue, now there is 30+ seconds:

1. D/MainActivity:501: Webcon executed
2. D/WebCon:109: DECISION LOGIC: DEFAULT - POST /sharebox_login 

**Take note of the two 10 and 17 second delays that have been constant over multiple tests**

```
09-22 11:07:41.999 30708-30708/no.sharebox.shareboxandroidapp D/MainActivity:501: Webcon executed

09-22 11:07:42.029 30708-30869/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-22 11:07:42.029 30708-30869/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Static: isShipBuild true
09-22 11:07:42.029 30708-30869/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Thread-21249-141691752: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
09-22 11:07:42.029 30708-30869/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-22 11:07:42.049 30708-30869/no.sharebox.shareboxandroidapp I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-22 11:07:42.139 30708-30779/no.sharebox.shareboxandroidapp W/GoogleTagManager: No container asset found in /assets/containers. Checking top level /assets directory for container assets.
09-22 11:07:42.259 30708-30779/no.sharebox.shareboxandroidapp W/GoogleTagManager: Tag Manager's event handler WILL NOT be installed (no container loaded)
09-22 11:07:42.259 30708-30779/no.sharebox.shareboxandroidapp I/GoogleTagManager: Tag Manager initilization took 241ms
09-22 11:07:42.269 30708-30779/no.sharebox.shareboxandroidapp D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-<hide-id>}]
09-22 11:07:42.279 30708-30779/no.sharebox.shareboxandroidapp V/FA: Using measurement service
09-22 11:07:42.279 30708-30779/no.sharebox.shareboxandroidapp V/FA: Connection attempt already in progress
 ... (10 sec wait) ...
09-22 11:07:52.019 30708-30786/no.sharebox.shareboxandroidapp W/Fabric: Could not call getAdvertisingIdInfo on com.google.android.gms.ads.identifier.AdvertisingIdClient
09-22 11:07:52.019 30708-30786/no.sharebox.shareboxandroidapp W/Fabric: Could not call isLimitAdTrackingEnabled on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
09-22 11:07:52.039 30708-30715/no.sharebox.shareboxandroidapp W/art: Suspending all threads took: 9.002ms
09-22 11:07:52.089 30708-30786/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-22 11:07:52.189 30708-30786/no.sharebox.shareboxandroidapp I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-22 11:07:53.510 30708-30794/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-22 11:07:53.640 30708-30794/no.sharebox.shareboxandroidapp I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-22 11:07:54.061 30708-30715/no.sharebox.shareboxandroidapp W/art: Suspending all threads took: 21.087ms
09-22 11:07:54.561 30708-31208/no.sharebox.shareboxandroidapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-22 11:07:54.611 30708-31208/no.sharebox.shareboxandroidapp I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-22 11:07:55.292 30708-31208/no.sharebox.shareboxandroidapp I/CrashlyticsCore: Crashlytics report upload complete: <hide-id>
  ... (17 sec wait) ...
09-22 11:08:12.018 30708-30841/no.sharebox.shareboxandroidapp W/InstanceID/Rpc: No response android.os.ConditionVariable@3972992
09-22 11:08:12.018 30708-30841/no.sharebox.shareboxandroidapp E/Intercom: Upload failed: TIMEOUT

09-22 11:08:12.048 30708-31595/no.sharebox.shareboxandroidapp D/WebCon:109: DECISION LOGIC: DEFAULT - POST /sharebox_login 

```
I have removed IDs from the log with <hide-id>

As of now I'm unsure if the Migration Helper is the cause anymore, but some other dependcy, will investigate further over the weekend.

**Comment by ashwinraghav** [comment] 2017-09-22 14:55
Like you pointed out, the logs do not seem to indicate that the problem is related to migration helpers. Have you tried removing the call and seeing if it persists ? I wish to reiterate that the migration helpers `migrate(true)` will delete the legacy digits tokens (if any) on the device and exchange them for a Firebase user. So the second time you call them on a device, it is a no-op. So repeated delays seem rather unlikely.
Please share if you have other findings. Thank you for working with us on this

**Comment by ashwinraghav** [comment] 2017-09-27 22:13
@HarisSistek Since we don't definitively know whether this is caused by the lib. I am closing the issue for now. Please reopen and add details if you feel this is still related to the library.

**Closed by ashwinraghav** 2017-09-27 22:13 UTC
